// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/master": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/set-password": {
    params: {};
  };
  "/:tenantSlug/login": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/auth/callback": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/reset-password": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/set-password": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/servicos": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/servicos/nova": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/servicos/agenda": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/servicos/relatorios": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/servicos/:id": {
    params: {
      "tenantSlug": string;
      "id": string;
    };
  };
  "/:tenantSlug/painel/zeladores": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/moradores": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/comunicados": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/assembleias": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/eventos": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/galeria": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/clube": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/guia": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/faq": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/arquivos": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/canal-morador": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel/configuracoes": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/painel": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/zelador": {
    params: {
      "tenantSlug": string;
    };
  };
  "/painel/servicos": {
    params: {};
  };
  "/painel/servicos/nova": {
    params: {};
  };
  "/painel/servicos/agenda": {
    params: {};
  };
  "/painel/servicos/relatorios": {
    params: {};
  };
  "/painel/servicos/:id": {
    params: {
      "id": string;
    };
  };
  "/painel/zeladores": {
    params: {};
  };
  "/painel/moradores": {
    params: {};
  };
  "/painel/comunicados": {
    params: {};
  };
  "/painel/assembleias": {
    params: {};
  };
  "/painel/eventos": {
    params: {};
  };
  "/painel/galeria": {
    params: {};
  };
  "/painel/clube": {
    params: {};
  };
  "/painel/guia": {
    params: {};
  };
  "/painel/faq": {
    params: {};
  };
  "/painel/arquivos": {
    params: {};
  };
  "/painel/canal-morador": {
    params: {};
  };
  "/painel/configuracoes": {
    params: {};
  };
  "/painel": {
    params: {};
  };
  "/zelador": {
    params: {};
  };
  "/painel-master": {
    params: {};
  };
  "/:tenantSlug/onboarding": {
    params: {
      "tenantSlug": string;
    };
  };
  "/onboarding": {
    params: {};
  };
  "/:tenantSlug/portal/comunicados": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/clube": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/guia": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/eventos": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/galeria": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/arquivos": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug/portal/faq": {
    params: {
      "tenantSlug": string;
    };
  };
  "/portal/comunicados": {
    params: {};
  };
  "/portal/clube": {
    params: {};
  };
  "/portal/guia": {
    params: {};
  };
  "/portal/eventos": {
    params: {};
  };
  "/portal/galeria": {
    params: {};
  };
  "/portal/arquivos": {
    params: {};
  };
  "/portal/faq": {
    params: {};
  };
  "/:tenantSlug/join": {
    params: {
      "tenantSlug": string;
    };
  };
  "/:tenantSlug": {
    params: {
      "tenantSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/auth/callback" | "/master" | "/reset-password" | "/set-password" | "/:tenantSlug/login" | "/:tenantSlug/auth/callback" | "/:tenantSlug/reset-password" | "/:tenantSlug/set-password" | "/:tenantSlug/painel/servicos" | "/:tenantSlug/painel/servicos/nova" | "/:tenantSlug/painel/servicos/agenda" | "/:tenantSlug/painel/servicos/relatorios" | "/:tenantSlug/painel/servicos/:id" | "/:tenantSlug/painel/zeladores" | "/:tenantSlug/painel/moradores" | "/:tenantSlug/painel/comunicados" | "/:tenantSlug/painel/assembleias" | "/:tenantSlug/painel/eventos" | "/:tenantSlug/painel/galeria" | "/:tenantSlug/painel/clube" | "/:tenantSlug/painel/guia" | "/:tenantSlug/painel/faq" | "/:tenantSlug/painel/arquivos" | "/:tenantSlug/painel/canal-morador" | "/:tenantSlug/painel/configuracoes" | "/:tenantSlug/painel" | "/:tenantSlug/zelador" | "/painel/servicos" | "/painel/servicos/nova" | "/painel/servicos/agenda" | "/painel/servicos/relatorios" | "/painel/servicos/:id" | "/painel/zeladores" | "/painel/moradores" | "/painel/comunicados" | "/painel/assembleias" | "/painel/eventos" | "/painel/galeria" | "/painel/clube" | "/painel/guia" | "/painel/faq" | "/painel/arquivos" | "/painel/canal-morador" | "/painel/configuracoes" | "/painel" | "/zelador" | "/painel-master" | "/:tenantSlug/onboarding" | "/onboarding" | "/:tenantSlug/portal/comunicados" | "/:tenantSlug/portal/clube" | "/:tenantSlug/portal/guia" | "/:tenantSlug/portal/eventos" | "/:tenantSlug/portal/galeria" | "/:tenantSlug/portal/arquivos" | "/:tenantSlug/portal/faq" | "/portal/comunicados" | "/portal/clube" | "/portal/guia" | "/portal/eventos" | "/portal/galeria" | "/portal/arquivos" | "/portal/faq" | "/:tenantSlug/join" | "/:tenantSlug";
  };
  "layout.tsx": {
    id: "layout";
    page: "/login" | "/auth/callback" | "/master" | "/reset-password" | "/set-password" | "/:tenantSlug/login" | "/:tenantSlug/auth/callback" | "/:tenantSlug/reset-password" | "/:tenantSlug/set-password" | "/:tenantSlug/painel/servicos" | "/:tenantSlug/painel/servicos/nova" | "/:tenantSlug/painel/servicos/agenda" | "/:tenantSlug/painel/servicos/relatorios" | "/:tenantSlug/painel/servicos/:id" | "/:tenantSlug/painel/zeladores" | "/:tenantSlug/painel/moradores" | "/:tenantSlug/painel/comunicados" | "/:tenantSlug/painel/assembleias" | "/:tenantSlug/painel/eventos" | "/:tenantSlug/painel/galeria" | "/:tenantSlug/painel/clube" | "/:tenantSlug/painel/guia" | "/:tenantSlug/painel/faq" | "/:tenantSlug/painel/arquivos" | "/:tenantSlug/painel/canal-morador" | "/:tenantSlug/painel/configuracoes" | "/:tenantSlug/painel" | "/:tenantSlug/zelador" | "/painel/servicos" | "/painel/servicos/nova" | "/painel/servicos/agenda" | "/painel/servicos/relatorios" | "/painel/servicos/:id" | "/painel/zeladores" | "/painel/moradores" | "/painel/comunicados" | "/painel/assembleias" | "/painel/eventos" | "/painel/galeria" | "/painel/clube" | "/painel/guia" | "/painel/faq" | "/painel/arquivos" | "/painel/canal-morador" | "/painel/configuracoes" | "/painel" | "/zelador" | "/painel-master" | "/:tenantSlug/onboarding" | "/onboarding" | "/:tenantSlug/portal/comunicados" | "/:tenantSlug/portal/clube" | "/:tenantSlug/portal/guia" | "/:tenantSlug/portal/eventos" | "/:tenantSlug/portal/galeria" | "/:tenantSlug/portal/arquivos" | "/:tenantSlug/portal/faq" | "/portal/comunicados" | "/portal/clube" | "/portal/guia" | "/portal/eventos" | "/portal/galeria" | "/portal/arquivos" | "/portal/faq" | "/:tenantSlug/join" | "/:tenantSlug" | "/";
  };
  "(auth)/login.tsx": {
    id: "login-global";
    page: "/login";
  } | {
    id: "login-tenant";
    page: "/:tenantSlug/login";
  } | {
    id: "tenant-login";
    page: "/:tenantSlug/login";
  };
  "(auth)/callback.tsx": {
    id: "callback-global";
    page: "/auth/callback";
  } | {
    id: "callback-tenant";
    page: "/:tenantSlug/auth/callback";
  };
  "(auth)/master-gateway.tsx": {
    id: "master-gateway";
    page: "/master";
  };
  "(auth)/reset-password.tsx": {
    id: "reset-password-global";
    page: "/reset-password";
  } | {
    id: "set-password-global";
    page: "/set-password";
  } | {
    id: "reset-password-tenant";
    page: "/:tenantSlug/reset-password";
  } | {
    id: "set-password-tenant";
    page: "/:tenantSlug/set-password";
  };
  "../components/layout/ProtectedRoute.tsx": {
    id: "../components/layout/ProtectedRoute";
    page: "/:tenantSlug/painel/servicos" | "/:tenantSlug/painel/servicos/nova" | "/:tenantSlug/painel/servicos/agenda" | "/:tenantSlug/painel/servicos/relatorios" | "/:tenantSlug/painel/servicos/:id" | "/:tenantSlug/painel/zeladores" | "/:tenantSlug/painel/moradores" | "/:tenantSlug/painel/comunicados" | "/:tenantSlug/painel/assembleias" | "/:tenantSlug/painel/eventos" | "/:tenantSlug/painel/galeria" | "/:tenantSlug/painel/clube" | "/:tenantSlug/painel/guia" | "/:tenantSlug/painel/faq" | "/:tenantSlug/painel/arquivos" | "/:tenantSlug/painel/canal-morador" | "/:tenantSlug/painel/configuracoes" | "/:tenantSlug/painel" | "/:tenantSlug/zelador" | "/painel/servicos" | "/painel/servicos/nova" | "/painel/servicos/agenda" | "/painel/servicos/relatorios" | "/painel/servicos/:id" | "/painel/zeladores" | "/painel/moradores" | "/painel/comunicados" | "/painel/assembleias" | "/painel/eventos" | "/painel/galeria" | "/painel/clube" | "/painel/guia" | "/painel/faq" | "/painel/arquivos" | "/painel/canal-morador" | "/painel/configuracoes" | "/painel" | "/zelador" | "/painel-master" | "/:tenantSlug/onboarding" | "/onboarding";
  };
  "../components/layout/DashboardLayout.tsx": {
    id: "../components/layout/DashboardLayout";
    page: "/:tenantSlug/painel/servicos" | "/:tenantSlug/painel/servicos/nova" | "/:tenantSlug/painel/servicos/agenda" | "/:tenantSlug/painel/servicos/relatorios" | "/:tenantSlug/painel/servicos/:id" | "/:tenantSlug/painel/zeladores" | "/:tenantSlug/painel/moradores" | "/:tenantSlug/painel/comunicados" | "/:tenantSlug/painel/assembleias" | "/:tenantSlug/painel/eventos" | "/:tenantSlug/painel/galeria" | "/:tenantSlug/painel/clube" | "/:tenantSlug/painel/guia" | "/:tenantSlug/painel/faq" | "/:tenantSlug/painel/arquivos" | "/:tenantSlug/painel/canal-morador" | "/:tenantSlug/painel/configuracoes" | "/:tenantSlug/painel" | "/:tenantSlug/zelador" | "/painel/servicos" | "/painel/servicos/nova" | "/painel/servicos/agenda" | "/painel/servicos/relatorios" | "/painel/servicos/:id" | "/painel/zeladores" | "/painel/moradores" | "/painel/comunicados" | "/painel/assembleias" | "/painel/eventos" | "/painel/galeria" | "/painel/clube" | "/painel/guia" | "/painel/faq" | "/painel/arquivos" | "/painel/canal-morador" | "/painel/configuracoes" | "/painel" | "/zelador" | "/painel-master";
  };
  "(dashboard)/servicos/index.tsx": {
    id: "tenant-admin-servicos";
    page: "/:tenantSlug/painel/servicos";
  } | {
    id: "admin-servicos";
    page: "/painel/servicos";
  };
  "(dashboard)/servicos/nova.tsx": {
    id: "tenant-admin-servicos-nova";
    page: "/:tenantSlug/painel/servicos/nova";
  } | {
    id: "admin-servicos-nova";
    page: "/painel/servicos/nova";
  };
  "(dashboard)/servicos/agenda.tsx": {
    id: "tenant-admin-servicos-agenda";
    page: "/:tenantSlug/painel/servicos/agenda";
  } | {
    id: "admin-servicos-agenda";
    page: "/painel/servicos/agenda";
  };
  "(dashboard)/servicos/relatorios.tsx": {
    id: "tenant-admin-servicos-relatorios";
    page: "/:tenantSlug/painel/servicos/relatorios";
  } | {
    id: "admin-servicos-relatorios";
    page: "/painel/servicos/relatorios";
  };
  "(dashboard)/servicos/[id].tsx": {
    id: "tenant-admin-servicos-detalhe";
    page: "/:tenantSlug/painel/servicos/:id";
  } | {
    id: "admin-servicos-detalhe";
    page: "/painel/servicos/:id";
  };
  "(dashboard)/zeladores/index.tsx": {
    id: "tenant-admin-zeladores";
    page: "/:tenantSlug/painel/zeladores";
  } | {
    id: "admin-zeladores";
    page: "/painel/zeladores";
  };
  "(dashboard)/moradores/index.tsx": {
    id: "tenant-admin-moradores";
    page: "/:tenantSlug/painel/moradores";
  } | {
    id: "admin-moradores";
    page: "/painel/moradores";
  };
  "(dashboard)/avisos/index.tsx": {
    id: "tenant-admin-comunicados";
    page: "/:tenantSlug/painel/comunicados";
  } | {
    id: "admin-comunicados";
    page: "/painel/comunicados";
  };
  "(dashboard)/assembleias/index.tsx": {
    id: "tenant-admin-assembleias";
    page: "/:tenantSlug/painel/assembleias";
  } | {
    id: "admin-assembleias";
    page: "/painel/assembleias";
  };
  "(dashboard)/eventos/index.tsx": {
    id: "tenant-admin-eventos";
    page: "/:tenantSlug/painel/eventos";
  } | {
    id: "admin-eventos";
    page: "/painel/eventos";
  };
  "(dashboard)/galeria/index.tsx": {
    id: "tenant-admin-galeria";
    page: "/:tenantSlug/painel/galeria";
  } | {
    id: "admin-galeria";
    page: "/painel/galeria";
  };
  "(dashboard)/clube/index.tsx": {
    id: "tenant-admin-clube";
    page: "/:tenantSlug/painel/clube";
  } | {
    id: "admin-clube";
    page: "/painel/clube";
  };
  "(dashboard)/guia-morador/index.tsx": {
    id: "tenant-admin-guia";
    page: "/:tenantSlug/painel/guia";
  } | {
    id: "admin-guia";
    page: "/painel/guia";
  };
  "(dashboard)/faq/index.tsx": {
    id: "tenant-admin-faq";
    page: "/:tenantSlug/painel/faq";
  } | {
    id: "admin-faq";
    page: "/painel/faq";
  };
  "(dashboard)/documentos/index.tsx": {
    id: "tenant-admin-docs";
    page: "/:tenantSlug/painel/arquivos";
  } | {
    id: "admin-docs";
    page: "/painel/arquivos";
  };
  "(dashboard)/canal-morador/index.tsx": {
    id: "tenant-admin-canal-morador";
    page: "/:tenantSlug/painel/canal-morador";
  } | {
    id: "admin-canal-morador";
    page: "/painel/canal-morador";
  };
  "(dashboard)/configuracoes/index.tsx": {
    id: "tenant-admin-settings";
    page: "/:tenantSlug/painel/configuracoes";
  } | {
    id: "admin-settings";
    page: "/painel/configuracoes";
  };
  "(dashboard)/home.tsx": {
    id: "tenant-admin-home";
    page: "/:tenantSlug/painel";
  } | {
    id: "admin-home";
    page: "/painel";
  };
  "(zelador)/index.tsx": {
    id: "tenant-zelador-home";
    page: "/:tenantSlug/zelador";
  } | {
    id: "zelador-home";
    page: "/zelador";
  };
  "(dashboard)/master-dashboard.tsx": {
    id: "painel-master";
    page: "/painel-master";
  };
  "(dashboard)/onboarding/index.tsx": {
    id: "tenant-onboarding";
    page: "/:tenantSlug/onboarding";
  } | {
    id: "onboarding";
    page: "/onboarding";
  };
  "(public)/comunicados.tsx": {
    id: "tenant-public-comunicados";
    page: "/:tenantSlug/portal/comunicados";
  } | {
    id: "public-comunicados";
    page: "/portal/comunicados";
  };
  "(public)/clube.tsx": {
    id: "tenant-public-clube";
    page: "/:tenantSlug/portal/clube";
  } | {
    id: "public-clube";
    page: "/portal/clube";
  };
  "(public)/guia.tsx": {
    id: "tenant-public-guia";
    page: "/:tenantSlug/portal/guia";
  } | {
    id: "public-guia";
    page: "/portal/guia";
  };
  "(public)/eventos.tsx": {
    id: "tenant-public-eventos";
    page: "/:tenantSlug/portal/eventos";
  } | {
    id: "public-eventos";
    page: "/portal/eventos";
  };
  "(public)/galeria.tsx": {
    id: "tenant-public-galeria";
    page: "/:tenantSlug/portal/galeria";
  } | {
    id: "public-galeria";
    page: "/portal/galeria";
  };
  "(public)/documentos.tsx": {
    id: "tenant-public-docs";
    page: "/:tenantSlug/portal/arquivos";
  } | {
    id: "public-docs";
    page: "/portal/arquivos";
  };
  "(public)/faq.tsx": {
    id: "tenant-public-faq";
    page: "/:tenantSlug/portal/faq";
  } | {
    id: "public-faq";
    page: "/portal/faq";
  };
  "(public)/join.tsx": {
    id: "tenant-join";
    page: "/:tenantSlug/join";
  };
  "(public)/landing.tsx": {
    id: "tenant-landing";
    page: "/:tenantSlug";
  } | {
    id: "global-landing";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layout": typeof import("./src/app/layout.tsx");
  "login-global": typeof import("./src/app/(auth)/login.tsx");
  "callback-global": typeof import("./src/app/(auth)/callback.tsx");
  "master-gateway": typeof import("./src/app/(auth)/master-gateway.tsx");
  "reset-password-global": typeof import("./src/app/(auth)/reset-password.tsx");
  "set-password-global": typeof import("./src/app/(auth)/reset-password.tsx");
  "login-tenant": typeof import("./src/app/(auth)/login.tsx");
  "callback-tenant": typeof import("./src/app/(auth)/callback.tsx");
  "reset-password-tenant": typeof import("./src/app/(auth)/reset-password.tsx");
  "set-password-tenant": typeof import("./src/app/(auth)/reset-password.tsx");
  "../components/layout/ProtectedRoute": unknown;
  "../components/layout/DashboardLayout": unknown;
  "tenant-admin-servicos": typeof import("./src/app/(dashboard)/servicos/index.tsx");
  "tenant-admin-servicos-nova": typeof import("./src/app/(dashboard)/servicos/nova.tsx");
  "tenant-admin-servicos-agenda": typeof import("./src/app/(dashboard)/servicos/agenda.tsx");
  "tenant-admin-servicos-relatorios": typeof import("./src/app/(dashboard)/servicos/relatorios.tsx");
  "tenant-admin-servicos-detalhe": typeof import("./src/app/(dashboard)/servicos/[id].tsx");
  "tenant-admin-zeladores": typeof import("./src/app/(dashboard)/zeladores/index.tsx");
  "tenant-admin-moradores": typeof import("./src/app/(dashboard)/moradores/index.tsx");
  "tenant-admin-comunicados": typeof import("./src/app/(dashboard)/avisos/index.tsx");
  "tenant-admin-assembleias": typeof import("./src/app/(dashboard)/assembleias/index.tsx");
  "tenant-admin-eventos": typeof import("./src/app/(dashboard)/eventos/index.tsx");
  "tenant-admin-galeria": typeof import("./src/app/(dashboard)/galeria/index.tsx");
  "tenant-admin-clube": typeof import("./src/app/(dashboard)/clube/index.tsx");
  "tenant-admin-guia": typeof import("./src/app/(dashboard)/guia-morador/index.tsx");
  "tenant-admin-faq": typeof import("./src/app/(dashboard)/faq/index.tsx");
  "tenant-admin-docs": typeof import("./src/app/(dashboard)/documentos/index.tsx");
  "tenant-admin-canal-morador": typeof import("./src/app/(dashboard)/canal-morador/index.tsx");
  "tenant-admin-settings": typeof import("./src/app/(dashboard)/configuracoes/index.tsx");
  "tenant-admin-home": typeof import("./src/app/(dashboard)/home.tsx");
  "tenant-zelador-home": typeof import("./src/app/(zelador)/index.tsx");
  "admin-servicos": typeof import("./src/app/(dashboard)/servicos/index.tsx");
  "admin-servicos-nova": typeof import("./src/app/(dashboard)/servicos/nova.tsx");
  "admin-servicos-agenda": typeof import("./src/app/(dashboard)/servicos/agenda.tsx");
  "admin-servicos-relatorios": typeof import("./src/app/(dashboard)/servicos/relatorios.tsx");
  "admin-servicos-detalhe": typeof import("./src/app/(dashboard)/servicos/[id].tsx");
  "admin-zeladores": typeof import("./src/app/(dashboard)/zeladores/index.tsx");
  "admin-moradores": typeof import("./src/app/(dashboard)/moradores/index.tsx");
  "admin-comunicados": typeof import("./src/app/(dashboard)/avisos/index.tsx");
  "admin-assembleias": typeof import("./src/app/(dashboard)/assembleias/index.tsx");
  "admin-eventos": typeof import("./src/app/(dashboard)/eventos/index.tsx");
  "admin-galeria": typeof import("./src/app/(dashboard)/galeria/index.tsx");
  "admin-clube": typeof import("./src/app/(dashboard)/clube/index.tsx");
  "admin-guia": typeof import("./src/app/(dashboard)/guia-morador/index.tsx");
  "admin-faq": typeof import("./src/app/(dashboard)/faq/index.tsx");
  "admin-docs": typeof import("./src/app/(dashboard)/documentos/index.tsx");
  "admin-canal-morador": typeof import("./src/app/(dashboard)/canal-morador/index.tsx");
  "admin-settings": typeof import("./src/app/(dashboard)/configuracoes/index.tsx");
  "admin-home": typeof import("./src/app/(dashboard)/home.tsx");
  "zelador-home": typeof import("./src/app/(zelador)/index.tsx");
  "painel-master": typeof import("./src/app/(dashboard)/master-dashboard.tsx");
  "tenant-onboarding": typeof import("./src/app/(dashboard)/onboarding/index.tsx");
  "onboarding": typeof import("./src/app/(dashboard)/onboarding/index.tsx");
  "tenant-public-comunicados": typeof import("./src/app/(public)/comunicados.tsx");
  "tenant-public-clube": typeof import("./src/app/(public)/clube.tsx");
  "tenant-public-guia": typeof import("./src/app/(public)/guia.tsx");
  "tenant-public-eventos": typeof import("./src/app/(public)/eventos.tsx");
  "tenant-public-galeria": typeof import("./src/app/(public)/galeria.tsx");
  "tenant-public-docs": typeof import("./src/app/(public)/documentos.tsx");
  "tenant-public-faq": typeof import("./src/app/(public)/faq.tsx");
  "public-comunicados": typeof import("./src/app/(public)/comunicados.tsx");
  "public-clube": typeof import("./src/app/(public)/clube.tsx");
  "public-guia": typeof import("./src/app/(public)/guia.tsx");
  "public-eventos": typeof import("./src/app/(public)/eventos.tsx");
  "public-galeria": typeof import("./src/app/(public)/galeria.tsx");
  "public-docs": typeof import("./src/app/(public)/documentos.tsx");
  "public-faq": typeof import("./src/app/(public)/faq.tsx");
  "tenant-login": typeof import("./src/app/(auth)/login.tsx");
  "tenant-join": typeof import("./src/app/(public)/join.tsx");
  "tenant-landing": typeof import("./src/app/(public)/landing.tsx");
  "global-landing": typeof import("./src/app/(public)/landing.tsx");
};